name: les_contextes

on: [push, pull_request]

jobs:
  contexte:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le type de trigger
        run: |
          echo "event_name = ${{ github.event_name }}"
          echo "actor      = ${{ github.actor }}"
          echo "ref        = ${{ github.ref }}"
          echo "ref_name   = ${{ github.ref_name }}"
          echo "sha        = ${{ github.sha }}"
          echo "head_ref   = ${{ github.head_ref }}"
          echo "base_ref   = ${{ github.base_ref }}"

      - name: Step uniquement sur PR
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "✅ Je tourne sur une PULL REQUEST"

      - name: Step uniquement sur push
        if: ${{ github.event_name == 'push' }}
        run: echo "✅ Je tourne sur un PUSH"
