name: fruits_et_noms_matrix

on: workflow_dispatch

jobs:
  phrase:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        fruit: [pomme, banane, mangue, orange]
        nom: [Michel, Awa, Fatou]

    steps:
      - name: Afficher la phrase
        run: |
          echo "${{ matrix.nom }} mange une ${{ matrix.fruit }}, et il adore Ã§a !"
